### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ttytm** [webui-dev/odin-webui#1]

**Comment by crystalthoughts** [comment]
Hello, what needs to be done to resolve this?

**Comment by ttytm** [comment]
Hey @crystalthoughts,

Sorry about the delay. The challenge with Odin was the implantation and communication with the WebUI C library on Windows.

**Comment by crystalthoughts** [comment]
Could you give more details? I can try and look into it if I know what to aim for

**Comment by ttytm** [comment]
I unfortunately cannot tell what the issue is. 

You would need to try.

For this, clone the repository. There already is a `feat/windows-support` branch you can check out which linked the libraries.

As there is no automated setup for Windows until it is confirmed to be working, download the WebUI windows msvc release manually from https://github.com/webui-dev/webui/releases/nightly. Move the contents (`webui-windows-msvc-x64` -> `webui`) into the root of the cloned odin-webui repo (just like the setup script on other platforms would do automatically. This is the best starting point I can give you.

After having this done you can try to run the examples. While building works, they won't start, the program terminates silently.

**Comment by ttytm** [comment]
This is the full log before the crash when trying to run the minimal example. Maybe @hassandraga has an idea.
```
[User] webui_new_window()
[User] webui_get_new_window_id()
[Core]          WebUI v2.5.0-Beta-1 (Microsoft Windows, Non-Encrypted)
[Core]          _webui_init()
[Core]          _webui_get_current_path()
[Core]          _webui_malloc([260])
[Core]          _webui_ptr_add(0x000001B90D7BE960)
[Core]          _webui_malloc([260])
[Core]          _webui_ptr_add(0x000001B90D7D1B60)
[User] webui_new_window_id([1])
[Core]          _webui_malloc([2296])
[Core]          _webui_ptr_add(0x000001B90D7D7810)
[Core]          _webui_malloc([260])
[Core]          _webui_ptr_add(0x000001B90D7D8820)
[Core]          _webui_malloc([260])
[Core]          _webui_ptr_add(0x000001B90D7D8A30)
[User] webui_new_window_id() -> New window #1 @ 0x000001B90D7D7810
[User] webui_new_window_id() -> New window Token 0x75B2939A (1974637466)
[User] webui_show([1])
[Core]          _webui_show([1])
[Core]          _webui_malloc([20])
[Core]          _webui_ptr_add(0x000001B90D7D1EB0)
[Core]          _webui_is_valid_url([<html>He...])
[Core]          _webui_show() -> Embedded HTML:
- - -[HTML]- - - - - - - - - -
<html>Hellope</html>
- - - - - - - - - - - - - - - -
[Core]          _webui_show_window(HTML, [1])
[Core]          _webui_get_free_port()
[Core]          _webui_port_is_used([26458])
[Core]          _webui_socket_test_listen_win32([26458])
[Core]          _webui_get_free_port()
[Core]          _webui_port_is_used([14205])
[Core]          _webui_socket_test_listen_win32([14205])
[Core]          _webui_malloc([32])
[Core]          _webui_ptr_add(0x000001B90D7CC950)
[Core]          _webui_malloc([22])
[Core]          _webui_ptr_add(0x000001B90D7D2030)
```

**Comment by ttytm** [comment]
> The warning fixes broke the functionality, I will work on it tomorrow.

I see, thanks for the info. It works when manually compiling with one of the earlier commits.

**Comment by ttytm** [comment]
@crystalthoughts 

Windows support is added. Until the upstream fixes are implemented you need to compile WebUI manually. After the fixes you can help the setup.ps1 script that will help you bootstrap WebUI. 

Assuming you have msvc set-up: 
For a quick manual setup of the WebUI C library odin-webui binds to, do inside the odin-webui directory:

```sh
git clone --filter=blob:none https://github.com/webui-dev/webui
cd webui
git checkout ce3dce4991919941431624292693821e5f1dcfdc
nmake
```

Move the build files from `./dist` to `./` (the root of the webui clone).

Then you can use it. 
E.g. move back to you odin-webui dir and run an example:
```sh
cd ..
odin run examples/call_odin.odin -file
```

**Comment by ttytm** [comment]
No more manual setup require just use `setup.ps1` on Windows.

Thanks @hassandraga :tada:

**Comment by crystalthoughts** [comment]
Thanks! Look forward to trying
