### ISSUE TITLE
Error enum is better as a bool

### ISSUE THREAD

**Issue by neroist** [webui-dev/odin-webui#5]
`Error` is simply an enum with only two values (`None` and `Failed`). Its better off being removed and using a bool to indicate success instead.

**Comment by ttytm** [comment]
Yep, a bool would work. There were some initial issues with regarding the context in the `proc "c"` it wasn't sure if the enum contains more values.

**Comment by neroist** [comment]
I realized an enum is needed for the `err != nil` style error checking, which is used in some examples or functions iirc. I'm trying to make an updated version of the bindings but I'm new to the language 😆

**Comment by ttytm** [comment]
Yes good point.

There are some occurrences that use a bool for checking if a result is `ok`.
Though the enum is more flexible, allowing to wrap the error in e.g. another union error type, using `#shared_nil`. So yeah, let's keep using it 🙂
